[env]
TERM = "xterm-256color"

[general]
import = ['~/.config/alacritty/themes/themes/iterm.toml']
working_directory = "/Users/tony/"

[window]
padding = { y = 3 }
opacity = 0.9
startup_mode = "SimpleFullscreen"

[font]
normal = { family = "Comic Mono", style = "Normal" }

